### ISSUE TITLE
what giga player?

### ISSUE THREAD

**Issue by xalee** [floft/feedback#3]
Hello, your link is the only resource i have found for a .gig player(/plugin) for lmms. maybe it's that i don't use github that much, but i am interested in using this wonderful resource and wonder how to d/l / acquire it? it seems to be only mentioned and not available

peace

**Comment by floft** [comment]
The versions of LMMS with GIG Player haven't officially been released, but you can download the 1.2.0-RC1 pre-release that should have it.

https://github.com/LMMS/lmms/releases
https://github.com/LMMS/lmms/releases/tag/v1.1.90

Feel free to reopen this if you have further questions.

**Comment by xalee** [comment]
aw :(
